Repository MyHookie/hookie_front, pull requests merged in 2022-12, with the labels that each got.

#5 글로벌 스타일 추가 #4
  src/index.jsx
  src/styles/GlobalStyle.js
  src/styles/Theme.js
  src/styles/Util.js
Labels: ⚙ 개발 환경 세팅

#13 Welcome 페이지 퍼블리싱
  src/App.jsx
  src/pages/Welcome/index.jsx
Labels: 🎨 마크업 & 스타일링

#18 회원가입 페이지 퍼블리싱
  src/App.jsx
  src/components/Form/FormInput/index.jsx
  src/components/Form/SignUpForm/index.jsx
  src/components/Title/index.jsx
  src/pages/Auth/Sign/index.jsx
  src/pages/Auth/SignUp/index.jsx
  src/styles/GlobalStyle.js
Labels: 🎨 마크업 & 스타일링

#20 welcome 페이지 버튼 클릭 시 해당 페이지로 이동하는 기능 구현
  src/pages/Welcome/index.jsx
Labels: ✨ 기능 개발

#26 Header, Navigation 부족한 속성 추가
  src/components/Post/PostItem/index.jsx
  src/components/common/BaseHeader/index.jsx
  src/components/common/ConfirmHeader/index.jsx
  src/components/common/Navigation/index.jsx
  src/components/common/SearchHeader/index.jsx
  src/pages/Home/index.jsx
Labels: 🎨 마크업 & 스타일링

#30 회원가입 페이지 기능 구현 전 폴더 구조 변경
  src/api/authAxios.js
  src/components/Form/SignUpForm/index.jsx
  src/components/FormInput/index.jsx
  src/pages/Auth/SignUp/index.jsx
Labels: 📃 문서 수정

#33 게시글 상세 페이지 UI 마크업 초안 구현
  src/components/Comment/CommentInput/index.jsx
  src/components/Comment/CommentItem/index.jsx
  src/pages/Post/PostDetail/index.jsx
Labels: 🎨 마크업 & 스타일링

#35 팔로워 페이지 UI 수정
  src/components/FollowerItem/dummyList.js
  src/components/FollowerItem/index.jsx
  src/pages/Profile/Follower/index.jsx
Labels: 🎨 마크업 & 스타일링

#36 홈페이지 기능 구현 (검색창, 모달창, 포스트이동)
  public/index.html
  src/assets/Hookie.png
  src/components/Modal/BottomSheet/BottomSheetContent.jsx
  src/components/Modal/BottomSheet/index.jsx
  src/components/Post/PostItem/index.jsx
  src/components/Post/PostList/index.jsx
  src/components/UserSearch/index.jsx
  src/components/common/BaseHeader/index.jsx
  src/components/common/SearchHeader/index.jsx
  src/pages/Home/index.jsx
  src/styles/Util.js
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#40 게시글 상세 페이지 UI 수정 및 모달창 기능 구현
  src/components/Comment/CommentItem/index.jsx
  src/components/Post/PostItem/index.jsx
  src/pages/Post/PostDetail/index.jsx
  src/styles/GlobalStyle.js
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#44 404 페이지 이전 페이지 이동 기능 추가
  src/pages/404/index.jsx
  src/pages/NotFound/index.jsx
Labels: ✨ 기능 개발

#46 회원가입 페이지 기능 구현
  src/api/authAxios.js
  src/api/emailValidAxios.js
  src/atoms/auth.js
  src/components/FormInput/index.jsx
  src/pages/Auth/SignUp/index.jsx
Labels: ✨ 기능 개발, 📬 API 통신

#49 에러 메시지 출력 CSS 마크업 수정
  src/components/FormInput/index.jsx
  src/pages/Auth/SignUp/index.jsx
Labels: 🎨 마크업 & 스타일링

#51 로그인 페이지 UI 작업
  src/components/AuthInputForm/index.jsx
  src/pages/Auth/Login/index.jsx
  src/pages/Auth/SignUp/index.jsx
Labels: 🎨 마크업 & 스타일링

#53 Upload 페이지 기능 구현
  .pnp.cjs
  .yarn/cache/big-integer-npm-1.6.51-1a244d8e1f-3d444173d1.zip
  .yarn/cache/broadcast-channel-npm-3.7.0-81ceba70bb-803794c48d.zip
  .yarn/cache/js-sha3-npm-0.8.0-decf3ddcfa-75df77c1fc.zip
  .yarn/cache/match-sorter-npm-6.3.1-ff3565ebb9-a4b02b676a.zip
  .yarn/cache/microseconds-npm-0.2.0-dbdb8ab8bb-22bfa8553f.zip
  .yarn/cache/nano-time-npm-1.0.0-6eca938be8-eef8548546.zip
  .yarn/cache/nanoid-npm-4.0.0-924f5c6312-7d5946df5c.zip
  .yarn/cache/oblivious-set-npm-1.0.0-8e7336b241-f31740ea9c.zip
  .yarn/cache/react-query-npm-3.39.2-8b9894ce38-83b199e66a.zip
  .yarn/cache/remove-accents-npm-0.4.2-7cb341092a-84a6988555.zip
  .yarn/cache/unload-npm-2.2.0-c40df6b4d0-88ba950c5f.zip
  package.json
  src/index.jsx
  src/pages/Post/PostUpload/index.jsx
  yarn.lock
Labels: ⚙ 개발 환경 세팅, ✨ 기능 개발, 🎨 마크업 & 스타일링

#54 게시물 상세 페이지 댓글 작성 기능 구현
  src/components/Comment/CommentInput/index.jsx
  src/components/Comment/CommentItem/index.jsx
  src/components/Comment/CommentList/index.jsx
  src/pages/Post/PostDetail/index.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#60 Dialog 모달창 구현
  public/index.html
  src/components/Modal/BottomSheet/index.jsx
  src/components/Modal/Dialog/index.jsx
  src/components/Modal/index.jsx
  src/components/Post/PostItem/index.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#61 로그인 페이지 기능구현
  src/api/authAxios.js
  src/components/AuthInputForm/index.jsx
  src/pages/Auth/Login/index.jsx
  src/pages/Auth/SignUp/index.jsx
Labels: ✨ 기능 개발, 📬 API 통신

#64 게시물 상세 페이지 세부 기능 구현
  src/components/Comment/CommentInput/index.jsx
  src/components/Comment/CommentItem/index.jsx
  src/pages/Post/PostDetail/index.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#67 응답 받은 데이터 가공 및 로컬스토리지에 토큰 저장
  src/App.jsx
  src/atoms/auth.js
  src/pages/Auth/Login/index.jsx
  src/pages/Auth/ProfileSetting/index.jsx
  src/pages/Auth/SignUp/index.jsx
  src/pages/Profile/ProfileEdit/index.jsx
  src/pages/Profile/ProfileSetting/index.jsx
Labels: 📬 API 통신

#69 채팅방 기능 구현
  src/Message/MessageInput/index.jsx
  src/Message/MessageInput/index.style.js
  src/Message/MessageItem/index.jsx
  src/Message/MessageItem/index.style.js
  src/Message/MessageItemYours/index.jsx
  src/Message/MessageItemYours/index.style.js
  src/pages/Chat/ChatDetail/chatData.json
  src/pages/Chat/ChatDetail/index.jsx
  src/pages/Chat/ChatDetail/index.style.js
  src/pages/Chat/index.jsx
Labels: ✨ 기능 개발

#75 프로필 페이지 UI 구현
  src/components/ProfileImageInput/index.jsx
  src/components/ProfileImageInput/index.style.js
  src/pages/Auth/ProfileSetting/index.jsx
  src/pages/Auth/ProfileSetting/index.style.js
Labels: 🎨 마크업 & 스타일링

#79 이미지 등록 UI 및 기능 구현
  src/App.jsx
  src/pages/Mypicks/index.jsx
  src/pages/Mypicks/index.style.js
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#77 팔로워 페이지 세부 기능 구현 & API 통신
  src/components/FollowerItem/index.jsx
  src/pages/Profile/Follower/index.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링, 📬 API 통신

#86 팔로워 페이지 팔로우/언팔로우 기능 구현
  src/components/FollowerItem/index.jsx
  src/pages/Profile/Follower/index.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링, 📬 API 통신

#85 프로필 페이지 설정 기능 구현
  src/components/AuthInputForm/index.jsx
  src/components/ProfileImageInput/index.jsx
  src/components/ProfileImageInput/index.style.js
  src/pages/Auth/Login/index.jsx
  src/pages/Auth/ProfileSetting/index.jsx
  src/pages/Auth/ProfileSetting/index.style.js
  src/pages/Home/index.jsx
Labels: ✨ 기능 개발, 📬 API 통신

#84 myPick 페이지 모달 구현
  public/index.html
  src/components/Message/MessageInput/index.jsx
  src/components/Message/MessageInput/index.style.js
  src/components/Message/MessageItem/index.jsx
  src/components/Message/MessageItem/index.style.js
  src/components/Message/MessageItemYours/index.jsx
  src/components/Message/MessageItemYours/index.style.js
  src/components/Modal/MyPickModal/index.jsx
  src/components/Modal/MyPickModal/index.style.js
  src/pages/Chat/ChatDetail/index.jsx
  src/pages/Mypicks/index.style.js
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#92 SnackBar 모달 구현, Navigation 기능 추가, 디자인 수정
  public/index.html
  src/components/Modal/SnackBar/index.jsx
  src/components/Post/PostItem/index.jsx
  src/components/common/Navigation/NavigationLink/index.jsx
  src/components/common/Navigation/index.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#93 프로필 페이지 UI 구현
  src/App.jsx
  src/api/profile.js
  src/components/Post/PostItem/index.jsx
  src/components/Post/PostList/index.jsx
  src/components/Profile/UserInfo/index.jsx
  src/components/Profile/UserInfo/index.styles.js
  src/components/common/Navigation/index.jsx
  src/pages/Home/index.styles.js
  src/pages/Profile/index.jsx
  src/pages/Profile/index.styles.js
Labels: 🎨 마크업 & 스타일링

#95 프로필 페이지 기능 구현
  src/App.jsx
  src/api/follow.js
  src/api/post.js
  src/components/Post/AlbumPostItem/index.jsx
  src/components/Post/AlbumPostItem/index.styles.js
  src/components/Post/PostList/index.jsx
  src/components/Post/PostList/index.styles.js
  src/components/Profile/ProfilePost/index.jsx
  src/components/Profile/ProfilePost/index.styles.js
  src/components/Profile/UserInfo/index.jsx
  src/pages/Home/index.jsx
  src/pages/Post/PostEdit/index.jsx
  src/pages/Post/PostUpload/index.jsx
  src/pages/Profile/Follower/index.jsx
  src/pages/Profile/index.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링, 📬 API 통신

#96 splash 화면 기능 구현
  src/api/tokenValid.js
  src/assets/speech-bubble.png
  src/pages/Splash/index.jsx
  src/pages/Splash/index.style.js
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#98 Bottom Sheet 애니메이션, UI 수정
  src/components/Modal/BottomSheet/BottomSheetContent/index.jsx
  src/components/Modal/BottomSheet/index.jsx
  src/components/Post/PostItem/index.jsx
  src/pages/Chat/ChatDetail/index.jsx
  src/pages/Chat/index.jsx
  src/pages/Profile/index.jsx
Labels: 🎨 마크업 & 스타일링

#101 프로필 세팅 페이지 UI, 기능 구현
  .eslintrc.json
  src/atoms/profileInfo.js
  src/components/AuthInputForm/index.jsx
  src/components/Profile/ProfileInfoForm/index.jsx
  src/components/Profile/ProfileInfoForm/index.styles.js
  src/components/Profile/UserInfo/index.jsx
  src/components/ProfileImageInput/index.jsx
  src/components/common/ConfirmHeader/index.jsx
  src/pages/Auth/ProfileSetting/index.jsx
  src/pages/Auth/ProfileSetting/index.style.js
  src/pages/Auth/SignUp/index.jsx
  src/pages/Profile/ProfileEdit/index.jsx
  src/pages/Profile/ProfileEdit/index.styles.js
Labels: ⚙ 개발 환경 세팅, ✨ 기능 개발, 🎨 마크업 & 스타일링, 📬 API 통신

#103 myPick 페이지 유효성 검사 및 이미지 등록 기능 구현
  src/Message/MessageInput/index.jsx
  src/Message/MessageInput/index.style.js
  src/Message/MessageItem/index.jsx
  src/Message/MessageItem/index.style.js
  src/Message/MessageItemYours/index.jsx
  src/Message/MessageItemYours/index.style.js
  src/components/Message/MessageInput/index.jsx
  src/pages/Mypicks/index.jsx
  src/pages/Mypicks/index.style.js
Labels: ✨ 기능 개발

#107 로그아웃 기능 구현
  .pnp.cjs
  .yarn/cache/recoil-persist-npm-4.2.0-8058958608-1c8a6be4bb.zip
  package.json
  src/App.jsx
  src/atoms/login.js
  src/pages/Profile/index.jsx
  src/pages/Splash/index.jsx
  yarn.lock
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#106 게시글 상세 페이지 API 통신 및 기능 구현
  src/components/Comment/CommentInput/index.jsx
  src/components/Comment/CommentItem/index.jsx
  src/components/Comment/CommentList/index.jsx
  src/components/Post/PostItem/index.jsx
  src/pages/Post/PostDetail/index.jsx
Labels: ✨ 기능 개발, 📬 API 통신

#110 팔로워 페이지 이동 기능 구현
  src/components/FollowerItem/index.jsx
  src/pages/Profile/Follower/index.jsx
Labels: ✨ 기능 개발

#111 홈페이지 부족한 기능 보충
  src/App.jsx
  src/components/Post/PostItem/index.jsx
  src/components/Post/PostItem/index.styles.js
  src/components/Profile/ProfilePost/index.jsx
  src/components/Profile/UserInfo/index.jsx
  src/components/common/ScrollToTop/index.jsx
  src/pages/Home/index.jsx
  src/pages/Post/PostEdit/index.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링, 😆 버그 해결

#113 유저 검색 페이지 검색 결과 에러 수정, debounce를 통한 최적화 진행
  src/api/search.js
  src/components/UserSearch/SearchedUser/index.jsx
  src/components/UserSearch/SearchedUser/index.styles 2.js
  src/components/UserSearch/SearchedUser/index.styles.js
  src/components/UserSearch/index.jsx
  src/components/UserSearch/index.styles 2.js
  src/hooks/useDebounceValue.js
Labels: ✨ 기능 개발, 🔨 리팩토링

#116 팔로잉 페이지 마크업 및 기능 구현
  src/components/FollowItem/index.jsx
  src/components/FollowerItem/dummyList.js
  src/pages/Profile/Follower/index.jsx
  src/pages/Profile/Following/index.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링, 📬 API 통신

#115 프로필 페이지 안에서 myPick 파트 마크업 및 API get, post 통신 기능 구현
  src/components/Profile/MyPickItems/MyPickItem/index.jsx
  src/components/Profile/MyPickItems/MyPickItem/index.style.js
  src/components/Profile/MyPickItems/index.jsx
  src/components/Profile/MyPickItems/index.style.js
  src/pages/Mypicks/index.jsx
  src/pages/Mypicks/index.style.js
  src/pages/Profile/index.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링, 📬 API 통신

#120 styled-components 파일 분리
  src/components/AuthInputForm/index.jsx
  src/components/common/Button/index.jsx
  src/pages/Auth/Login/index.jsx
  src/pages/Auth/Login/index.style.js
  src/pages/Auth/ProfileSetting/index.jsx
  src/pages/Auth/SignUp/index.jsx
  src/pages/Auth/SignUp/index.style.js
Labels: 🎨 마크업 & 스타일링, 🔨 리팩토링

#121 팔로우/팔로잉 페이지 오류 수정
  src/components/FollowItem/index.jsx
  src/pages/Profile/Follower/index.jsx
  src/pages/Profile/Following/index.jsx
Labels: 😆 버그 해결

#122 포스트 수정 버그 해결, textarea 폰트 스타일 변경(전역)
  src/components/Post/PostItem/index.jsx
  src/components/Post/Posting/index.jsx
  src/components/Profile/ProfilePost/index.jsx
  src/index.jsx
  src/pages/Home/index.jsx
  src/pages/Post/PostEdit/index.jsx
  src/styles/GlobalStyle.js
Labels: 🎨 마크업 & 스타일링, 😆 버그 해결

#124 프로필 이동 시 내 프로필로 돌아와도 내 프로필로 변하지 않는 현상 해결
  src/components/Profile/UserInfo/index.jsx
  src/index.jsx
Labels: 😆 버그 해결

#128 게시글 상세 페이지 오류 수정
  src/api/comment.js
  src/api/post.js
  src/components/Comment/CommentInput/index.jsx
  src/components/Comment/CommentItem/index.jsx
  src/components/Post/PostItem/index.jsx
  src/components/Post/PostItem/index.styles.js
  src/pages/Post/PostDetail/index.jsx
Labels: 😆 버그 해결

#126 채팅 페이지, myPick 오류 수정
  src/components/Profile/MyPick/MyPickItem/index.jsx
  src/components/Profile/MyPick/MyPickItem/index.style.js
  src/components/Profile/MyPick/MyPickModal/index.jsx
  src/components/Profile/MyPick/MyPickModal/index.style.js
  src/components/Profile/MyPick/index.jsx
  src/components/Profile/MyPick/index.style.js
  src/pages/Chat/ChatDetail/index.jsx
  src/pages/Chat/index.jsx
  src/pages/Mypicks/index.jsx
  src/pages/Profile/index.jsx
Labels: 😆 버그 해결

#129 MyPick 파일명으로 인한 에러 해결 PR
  src/App.jsx
  src/components/Modal/MyPickModal/index.jsx
  src/components/Profile/MyPick/MyPickModal/index.style.js
  src/components/Profile/MyPicks/MyPickItem/index.jsx
  src/components/Profile/MyPicks/MyPickItem/index.style.js
  src/components/Profile/MyPicks/MyPickModal/index.jsx
  src/components/Profile/MyPicks/MyPickModal/index.style.js
  src/components/Profile/MyPicks/index.jsx
  src/components/Profile/MyPicks/index.style.js
  src/pages/MyPicksUpload/index.jsx
  src/pages/MyPicksUpload/index.style.js
  src/pages/Profile/index.jsx
Labels: 😆 버그 해결

#130 게시글 상세 페이지 추가 기능 구현
  src/components/Comment/CommentInput/index.jsx
  src/components/Comment/CommentItem/index.jsx
  src/components/Comment/CommentList/index.jsx
  src/pages/Post/PostDetail/index.jsx
Labels: ✨ 기능 개발, 😆 버그 해결, 🔨 리팩토링

#133 프로필 수정에서 accountName을 변경할 수 없도록 수정, 프로필 수정 코드 리팩토링
  src/api/authAxios.js
  src/components/AuthInputForm/index.jsx
  src/components/Profile/ProfileInfoForm/index.jsx
  src/components/Profile/UserInfo/index.styles.js
  src/components/ProfileImageInput/index.jsx
  src/components/ProfileImageInput/index.style.js
  src/pages/Profile/ProfileEdit/index.jsx
Labels: ✨ 기능 개발, 🔨 리팩토링

#135 유효성 검사 후 가입하지 않은 이메일임에도 가입 되었다는 오류
  src/pages/Auth/SignUp/index.jsx
Labels: 🐞 버그

#139 myPick 모달 상세 내용 보기 구현
  src/components/Profile/MyPicks/MyPickItem/index.jsx
  src/components/Profile/MyPicks/MyPickModal/index.jsx
  src/components/Profile/MyPicks/MyPickModal/index.style.js
  src/components/Profile/MyPicks/index.jsx
Labels: ✨ 기능 개발, 📬 API 통신

#143 다른 팔로워의 프로필 페이지에서 홈페이지로 이동하면 발생하는 키에러 수정
  src/components/Profile/ProfilePost/index.jsx
  src/components/Profile/UserInfo/index.jsx
Labels: 😆 버그 해결

#144 프로필, 게시글 업로드에서 HEIC 파일이 등록되도록 구현
  .pnp.cjs
  .yarn/cache/heic2any-npm-0.0.3-d4a7f6c1f3-83624b7c16.zip
  package.json
  src/components/Post/Posting/index.jsx
  src/components/ProfileImageInput/index.jsx
  yarn.lock
Labels: ⚙ 개발 환경 세팅, ✨ 기능 개발

#145 검색페이지 Loading Indicator 적용
  src/components/Skeleton/Search/index.jsx
  src/components/UserSearch/index.jsx
  src/styles/Util.js
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#149 게시글 상세 페이지 2차 오류 수정
  src/components/Comment/CommentInput/index.jsx
  src/components/Post/PostItem/index.jsx
  src/pages/Post/PostDetail/index.jsx
Labels: 🎨 마크업 & 스타일링, 😆 버그 해결

#150 다크모드 라이트모드 기능 추가
  src/App.jsx
  src/atoms/darkMode.js
  src/components/AuthInputForm/index.jsx
  src/components/ChatUserItem/index.jsx
  src/components/Comment/CommentInput/index.jsx
  src/components/Comment/CommentItem/index.jsx
  src/components/FollowItem/index.jsx
  src/components/Message/MessageInput/index.style.js
  src/components/Message/MessageItem/index.style.js
  src/components/Message/MessageItemYours/index.style.js
  src/components/Modal/BottomSheet/BottomSheetContent/index.jsx
  src/components/Modal/BottomSheet/index.jsx
  src/components/Modal/Dialog/index.jsx
  src/components/Modal/SnackBar/index.jsx
  src/components/Post/AlbumPostItem/index.styles.js
  src/components/Post/PostItem/index.styles.js
  src/components/Post/Posting/index.styles.js
  src/components/Post/PreviewImageItem/index.jsx
  src/components/Post/TagItem/index.jsx
  src/components/Profile/ProfileInfoForm/index.styles.js
  src/components/Profile/ProfilePost/index.styles.js
  src/components/Profile/UserInfo/index.styles.js
  src/components/ProfileImageInput/index.style.js
  src/components/Skeleton/Search/index.jsx
  src/components/UserSearch/SearchedUser/index.styles.js
  src/components/UserSearch/index.styles.js
  src/components/common/BaseHeader/index.jsx
  src/components/common/Button/index.jsx
  src/components/common/ConfirmHeader/index.jsx
  src/components/common/Navigation/NavigationLink/index.jsx
  src/components/common/Navigation/index.jsx
  src/components/common/SearchHeader/index.jsx
  src/index.jsx
  src/pages/Auth/Login/index.style.js
  src/pages/Auth/ProfileSetting/index.style.js
  src/pages/Chat/ChatDetail/index.style.js
  src/pages/Home/index.styles.js
  src/pages/NotFound/index.jsx
  src/pages/Post/PostDetail/index.jsx
  src/pages/Profile/index.jsx
  src/pages/Profile/index.styles.js
  src/pages/Welcome/index.jsx
  src/routes/Router.jsx
  src/styles/GlobalStyle.js
  src/styles/Theme.js
  src/styles/Util.js
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#152 팔로워/팔로잉 페이지 스타일 분리 및 오류 수정
  src/components/FollowItem/index.jsx
  src/components/FollowItem/index.styles.js
  src/pages/Profile/Follower/index.jsx
  src/pages/Profile/Follower/index.styles.js
  src/pages/Profile/Following/index.jsx
  src/pages/Profile/Following/index.styles.js
Labels: 🎨 마크업 & 스타일링, 😆 버그 해결
