Repository MyHookie/hookie_front, pull requests merged in 2023-01, with the labels that each got.

#157 myPick 삭제, 수정 기능 구현
  src/components/MyPicks/MyPickForm/index.jsx
  src/components/MyPicks/MyPickForm/index.style.js
  src/components/MyPicks/MyPickItem/index.jsx
  src/components/MyPicks/MyPickItem/index.style.js
  src/components/MyPicks/MyPickModal/index.jsx
  src/components/MyPicks/MyPickModal/index.style.js
  src/components/MyPicks/index.jsx
  src/components/MyPicks/index.style.js
  src/components/Profile/MyPicks/MyPickModal/index.jsx
  src/pages/MyPicks/MyPicksEdit/index.jsx
  src/pages/MyPicks/MyPicksEdit/index.style.js
  src/pages/MyPicks/MyPicksUpload/index.jsx
  src/pages/MyPicks/MyPicksUpload/index.style.js
  src/pages/Profile/index.jsx
  src/routes/Router.jsx
  src/styles/Theme.js
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링, 📬 API 통신

#155 홈페이지, 프로필 페이지 Loading Indicator 적용
  src/components/Profile/ProfilePost/index.jsx
  src/components/Profile/ProfilePost/index.styles.js
  src/components/Profile/UserInfo/index.jsx
  src/components/Profile/UserInfo/index.styles.js
  src/components/Skeleton/PostSkeleton/index.jsx
  src/pages/Auth/ProfileSetting/index.style.js
  src/pages/Home/index.jsx
  src/pages/Home/index.styles.js
  src/styles/Util.js
Labels: 🎨 마크업 & 스타일링

#164 myPick 삭제시 새로고침 해야 반영되는 오류 해결
  src/components/MyPicks/MyPickModal/index.jsx
  src/components/MyPicks/index.jsx
  src/pages/MyPicks/MyPicksEdit/index.jsx
  src/pages/MyPicks/MyPicksUpload/index.jsx
Labels: 😆 버그 해결

#165 개행한 문자열이 포스트에서 보이지 않던 현상 해결
  src/components/Post/PostItem/index.jsx
  src/components/Post/PostItem/index.styles.js
Labels: 🎨 마크업 & 스타일링

#167 myPick UI/UX 개선 이슈
  src/assets/icon/icon-arrow-left-grey.png
  src/assets/icon/icon-delete.png
  src/assets/icon/icon-home-fill.png
  src/assets/icon/icon-pen.png
  src/components/MyPicks/MyPickForm/index.style.js
  src/components/MyPicks/MyPickModal/index.jsx
  src/components/MyPicks/MyPickModal/index.style.js
  src/components/MyPicks/index.jsx
  src/pages/MyPicks/MyPicksEdit/index.jsx
  src/pages/MyPicks/MyPicksEdit/index.style.js
  src/pages/MyPicks/MyPicksUpload/index.jsx
  src/pages/MyPicks/MyPicksUpload/index.style.js
  src/styles/Theme.js
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#174 다크모드 화살표 아이콘 적용
  src/App.jsx
  src/atoms/theme.js
  src/components/common/BaseHeader/index.jsx
  src/components/common/ConfirmHeader/index.jsx
  src/hooks/useTheme.js
Labels: 🎨 마크업 & 스타일링

#175 이미지 3장 이상 등록 경고를 SnackBar로 변경, Loading Indicator 추가
  src/components/Post/Posting/index.jsx
  src/components/Skeleton/ImageSkeleton/index.jsx
  src/components/Skeleton/ImageSkeleton/index.styles.js
  src/components/Skeleton/PostSkeleton/index.jsx
  src/components/Skeleton/PostSkeleton/index.styles.js
  src/components/Skeleton/SearchSkeleton/index.jsx
  src/components/Skeleton/SearchSkeleton/index.styles.js
  src/components/UserSearch/index.jsx
Labels: ✨ 기능 개발, 🎨 마크업 & 스타일링

#176 index.html 메타 태그 설정 - 파비콘 설정 및 오픈그래프, 트위터카드 등록
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
Labels: ♿️ 웹 접근성

#178 홈페이지, 프로필 페이지 기능 수정
  .pnp.cjs
  .yarn/cache/react-intersection-observer-npm-9.4.1-d6fc91f3de-13d1c36658.zip
  package.json
  src/api/post.js
  src/components/Post/PostList/index.jsx
  src/components/Post/PostList/index.styles.js
  src/components/Profile/ProfilePost/index.jsx
  src/components/Profile/ProfilePost/index.styles.js
  src/pages/Home/index.jsx
  src/pages/Home/index.styles.js
  yarn.lock
Labels: ⚙ 개발 환경 세팅, ✨ 기능 개발

#168 게시글 상세 페이지 스타일 분리 및 추가 기능 구현
  src/components/Comment/CommentInput/index.jsx
  src/components/Comment/CommentInput/index.styles.js
  src/components/Comment/CommentItem/index.jsx
  src/components/Comment/CommentItem/index.styles.js
  src/components/Comment/CommentList/index.jsx
  src/components/Comment/CommentList/index.styles.js
  src/pages/Post/PostDetail/index.jsx
  src/pages/Post/PostDetail/index.styles.js
Labels: 🎨 마크업 & 스타일링, 😆 버그 해결

#180 옵셔널 체이닝으로 cannot read properties 오류 해결
  src/pages/Post/PostDetail/index.jsx
Labels: 😆 버그 해결

#182 팔로잉/팔로워 페이지 api 분리 및 모든 유저가 보이도록 구현
  src/api/follow.js
  src/components/FollowItem/index.jsx
  src/pages/Profile/Follower/index.jsx
  src/pages/Profile/Following/index.jsx
Labels: 🔨 리팩토링, 📬 API 통신

#183 다크모드용 로고 이미지 추가 및 적용
  src/assets/logo_darkmode.png
  src/pages/Splash/index.jsx
Labels: 🎨 마크업 & 스타일링

#184 콘솔로그 제거, 안쓰이는 모듈 제거
  src/App.jsx
  src/api/follow.js
  src/components/Message/MessageInput/index.style.js
  src/components/MyPicks/MyPickModal/index.jsx
  src/components/MyPicks/index.jsx
  src/components/Profile/ProfilePost/index.jsx
  src/components/Profile/UserInfo/index.jsx
  src/components/UserSearch/index.jsx
  src/components/common/Navigation/NavigationLink/index.jsx
  src/components/common/ScrollToTop/index.jsx
  src/hooks/useDebounceValue.js
  src/pages/Auth/Login/index.jsx
  src/pages/Chat/ChatDetail/index.jsx
  src/pages/Chat/index.jsx
  src/pages/MyPicks/MyPicksEdit/index.jsx
  src/pages/MyPicks/MyPicksUpload/index.jsx
  src/pages/Post/PostEdit/index.jsx
  src/routes/Router.jsx
Labels: 📃 문서 수정

#186 게시글 상세 페이지 모든 댓글이 보이도록 구현
  src/api/comment.js
Labels: 🔨 리팩토링, 📬 API 통신

#187 채팅 페이지 더미텍스트 변경
  src/components/Message/MessageItemYours/index.style.js
  src/pages/Chat/ChatDetail/chatData.json
  src/pages/Chat/ChatDetail/index.jsx
  src/pages/Chat/index.jsx
Labels: 🎨 마크업 & 스타일링

#190 다른 프로젝트의 계정의 글에 접근할 경우 발생하는 에러 해결
  src/components/Post/PostItem/index.jsx
Labels: 😆 버그 해결

#192 댓글 클릭시 프로필 페이지 이동하도록 구현
  src/components/Comment/CommentItem/index.jsx
Labels: ✨ 기능 개발
